### ISSUE TITLE
Example `npm start` is broken (literal expression editor does not open)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-dmn-js#119]
The example in `npm start` is broken, literal expression editor blows up.

#### Steps to reproduce

* `npm start`
* Open literal expression from DRD editor
* :boom: 

#### Capture (demo)

![capture Z10pKn_optimized](https://github.com/user-attachments/assets/658322d0-f900-4d0f-81ce-c7bd9a44fc26)

----

_Originally posted by @nikku in https://github.com/camunda/camunda-dmn-js/issues/118#issuecomment-2304289151_

**Comment by barmac** [comment]
Thanks for reporting. I'll have a look at this.

**Comment by barmac** [comment]
The example is a valid DMN, and the issue is within the dmn-js-literal-expression library. In that project, we [assume that the decision contains a variable element](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js#L19) which is optional in DMN, but always created in dmn-js-drd.
Temporary solution is to change the example to meet the assumption. The correct solution would be to properly handle missing variable in literal expression: add it if missing, and make the name follow the decision name. However, I believe we will replace dmn-js-literal-expression with dmn-js-boxed-expression at some point of time, so for now I will only implement the diagram change.
